name: Build and Deploy to S3

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Specify your Java version here

      # Step 3: Build the project with Maven
      - name: Build the project
        run: mvn clean package

      # Step 4: Upload to S3
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          sudo apt-get install -y awscli
          aws s3 cp target/demo-0.0.1-SNAPSHOT.jar.jar s3://$AWS_BUCKET_NAME/demo-0.0.1-SNAPSHOT.jar --region $AWS_REGION
