name: Build and Deploy to S3

# Trigger the workflow on pushes to the master branch
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 3: Build the project with Maven
      - name: Build the project
        run: mvn clean package

      # Optional: List target directory contents for debugging
      - name: List target directory contents
        run: ls target

      # Debugging Step
      - name: Debug environment variables
        run: |
          echo "AWS_BUCKET: $AWS_BUCKET"
          echo "AWS_REGION: $AWS_REGION"

      # Step 4: Upload to S3
      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws s3 cp target/demo-0.0.1-SNAPSHOT.jar s3://github-lav/demo-0.0.1-SNAPSHOT.jar --region $AWS_REGION
