name: Deploy Angular App to IIS

on:
  push:
    branches:
      - main  # Trigger the workflow on changes to the 'main' branch

jobs:
  deploy:
    runs-on: windows-latest  # Use a Windows runner (or self-hosted runner with IIS installed)

    steps:
    # Step 1: Checkout the Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set Up Node.js and Install Dependencies
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version

    - name: Install Angular CLI
      run: npm install -g @angular/cli@14  # Specify the Angular CLI version to use

    - name: Install project dependencies
      run: npm install

    # Step 3: Build the Angular Application
    - name: Build Angular project
      run: ng build --configuration production  # Build the Angular project for production

    # Step 4: Deploy to IIS
    - name: Deploy to IIS
      run: |
        # Define paths
        $source = "D:\a\angularApp-deployment\angularApp-deployment\dist\my-angular9-app"  # Angular build output path
        $destination = "C:\inetpub\wwwroot\my-angular9-app"  # IIS app folder

        Write-Host "Source Path: $source"
        Write-Host "Destination Path: $destination"

        # Check source path
        if (-not (Test-Path -Path $source)) {
            Write-Error "Source path does not exist: $source"
            exit 1
        } else {
            Write-Host "Source path exists: $source"
        }

        # Ensure destination folder exists
        if (-not (Test-Path -Path $destination)) {
            Write-Host "Destination does not exist. Creating it."
            New-Item -ItemType Directory -Path $destination
        }

        # Clean destination folder
        Remove-Item -Path "$destination\*" -Recurse -Force -ErrorAction SilentlyContinue

        # Copy files
        Copy-Item -Path "$source\*" -Destination $destination -Recurse -Force
        Write-Host "Files copied successfully."

        # Restart IIS
        iisreset /restart
        Write-Host "IIS restarted. Deployment complete."
      shell: pwsh
